version: "2.1"

services:
  generate-ssl-certificate:
    image: nginx:1.11
    environment:
      - NGINX_SERVER_NAME
    command: openssl req -newkey rsa:2048 -nodes -keyout "${NGINX_SERVER_NAME}.key" -x509 -days 365 -out "${NGINX_SERVER_NAME}.crt" -subj "${X509_CERTIFICATE_SUBJECT}"
    volumes:
      - ${PWD}/.ssl:/var/tmp
    working_dir: /var/tmp
